Feature signup login page
OsmanRana/fun-kickoff-project pull request #1
Opened 2022-01-07 14:23 UTC by OsmanRana

### What this PR does (required):
- list PR functionality here
- Changed the login/logout button and the button text as per mock up.
- Made Title bold.
- Form TextField variant="standard" added.

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**
- 
![login-page](https://user-images.githubusercontent.com/86624150/148557298-3c0f13bd-7429-4cb8-8434-e2208e272ae6.png)

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2022-01-07 20:23 UTC, rajivtitus reviewed
Good start! Please match the UI to the mocks given

2022-01-07 20:26 UTC, rajivtitus requested changes
Please complete this feature

2022-01-08 18:05 UTC, OsmanRana commented
### What this PR does (required):
Edited signup and login page

### Screenshots / Videos (front-end only):
![signup](https://user-images.githubusercontent.com/86624150/148654770-17e56363-23f3-4a46-bb29-97251cbbaec8.png)
![login](https://user-images.githubusercontent.com/86624150/148654776-28a448b0-a199-4511-9c14-8b6793402699.png)

2022-01-10 18:07 UTC, moffatethan requested changes
Just some minor changes, otherwise pretty good.

2022-01-10 18:07 UTC, moffatethan commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +                  border: '1px solid #f14140',
I think just the default MUI hover state is fine and less of an big color change.

2022-01-10 18:07 UTC, moffatethan commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +            <InputLabel className={classes.inputLabel}>
Probably could've made this a reusable component.

2022-01-21 07:03 UTC, merged